In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [7]:
df_data = pd.read_csv('./data_total_cluster_articulo_final_5.csv')

In [8]:
df_data.head(1)

,creado,fecha,proyecto,vendedor,tipo_de_cliente,cliente,cantidad,articulo,costo,impresión,...,navaja,audífonos,pañalera,bata,mascarilla,almohada,peluche,termómetro,cluster_names,articulo_unico
0,2018-10-29 10:15:30,2018-10-01,PS1808080202,CRISTIAN HERNANDEZ,RECURRENTE,VMACS,10.0,HIELERA,88.07,0.0,...,0,0,0,0,0,0,0,0,missing,missing

In [10]:
df_data_2022 = df_data[df_data.fecha.between('2022-01-01', '2023-01-01')]
df_data_2019 = df_data[df_data.fecha.between('2019-01-01', '2020-01-01')]
df_data_2021 = df_data[df_data.fecha.between('2021-01-01', '2022-01-01')]

In [12]:
df_data_19_21_22 = pd.concat([df_data_2019,df_data_2019, df_data_2021], ignore_index=True)

In [24]:
df_data_19_21_22.columns[-20:]

Index(['sombrilla', 'abanico', 'impermeable', 'binoculares', 'encendedor',
       'ventilador', 'post_it', 'pluma', 'pastillero', 'cangurera', 'navaja',
       'audífonos', 'pañalera', 'bata', 'mascarilla', 'almohada', 'peluche',
       'termómetro', 'cluster_names', 'articulo_unico'],
      dtype='object')

In [26]:
df_fecha_articulo = df_data_19_21_22.drop(columns=['creado', 'proyecto', 'vendedor', 'tipo_de_cliente', 'cliente',
                       'cantidad', 'articulo', 'costo', 'impresión', 'precio', 'total',
                       'mermas', 'paqueteria_o_gasto_extra', 'utilidad_real', 'inversion',
                       'utilidad_real/cantidad', 'cluster_names', 'articulo_unico'])

In [ ]:
df_fecha_articulo['fecha']=pd.to_datetime(df_fecha_articulo.fecha)

In [34]:
df_fecha_articulo_tabla = df_fecha_articulo.groupby(df_fecha_articulo.fecha.dt.month).sum()

In [38]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [39]:
df_fecha_articulo_tabla_escalado = scaler.fit_transform(df_fecha_articulo_tabla)

In [59]:
df_fecha_articulo_tabla_escalado.head(1)

,bolsa,destapadores,llavero,antiestrés,inflables,banderines,alcancías,botella,termo,cilindro,...,pastillero,cangurera,navaja,audífonos,pañalera,bata,mascarilla,almohada,peluche,termómetro
0,-0.316544,1.604515,-0.29821,-0.088911,-0.301511,-0.301511,-0.61667,-0.868243,-0.355036,-2.144315,...,-1.133893,-0.548821,-0.603023,-0.650945,-0.301511,0.0,0.0,-0.420084,-0.301511,0.0

In [60]:
lista_mes=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']

In [62]:
df_fecha_articulo_tabla_escalado.

SyntaxError: invalid syntax (1958308185.py, line 1)

In [41]:
df_fecha_articulo_tabla_escalado = pd.DataFrame(df_fecha_articulo_tabla_escalado , columns=df_fecha_articulo_tabla.columns)

In [70]:
df = df_fecha_articulo_tabla_escalado.T

In [72]:
df.columns = lista_mes

In [75]:
df_fecha_articulo_tabla_escalado = df.T

In [44]:
from scipy.spatial.distance import pdist, squareform

In [76]:
distancias_mes_19_21_22 = pd.DataFrame(1/(1 + squareform(pdist(df_fecha_articulo_tabla_escalado))), columns = df_fecha_articulo_tabla_escalado.index, index = df_fecha_articulo_tabla_escalado.index)

In [77]:
distancias_mes_19_21_22

,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
enero,1.000000,0.078663,0.088704,0.065261,0.071638,0.069513,0.073727,0.069716,0.062714,0.074194,0.063115,0.089980
febrero,0.078663,1.000000,0.077427,0.063966,0.063304,0.070323,0.065680,0.066436,0.057743,0.066411,0.063046,0.071727
marzo,0.088704,0.077427,1.000000,0.068977,0.072087,0.073442,0.072309,0.068862,0.064595,0.077237,0.063732,0.076221
abril,0.065261,0.063966,0.068977,1.000000,0.066454,0.060082,0.061589,0.059963,0.054940,0.065752,0.061417,0.061635
mayo,0.071638,0.063304,0.072087,0.066454,1.000000,0.065588,0.068218,0.062491,0.059787,0.069848,0.066540,0.063650
junio,0.069513,0.070323,0.073442,0.060082,0.065588,1.000000,0.074271,0.062156,0.064691,0.077877,0.065910,0.065932
julio,0.073727,0.065680,0.072309,0.061589,0.068218,0.074271,1.000000,0.067369,0.059224,0.081046,0.063671,0.063574
agosto,0.069716,0.066436,0.068862,0.059963,0.062491,0.062156,0.067369,1.000000,0.058151,0.064242,0.057569,0.068017
septiembre,0.062714,0.057743,0.064595,0.054940,0.059787,0.064691,0.059224,0.058151,1.000000,0.067352,0.058959,0.061223
octubre,0.074194,0.066411,0.077237,0.065752,0.069848,0.077877,0.081046,0.064242,0.067352,1.000000,0.075732,0.064489
noviembre,0.063115,0.063046,0.063732,0.061417,0.066540,0.065910,0.063671,0.057569,0.058959,0.075732,1.000000,0.059102
diciembre,0.089980,0.071727,0.076221,0.061635,0.063650,0.065932,0.063574,0.068017,0.061223,0.064489,0.059102,1.000000

def recomendaciones_cliente(cliente):
    distancias_cliente = distancias_cliente_2022[cliente].drop(index = [cliente])
    df_resto = df_data_cliente_2022.T.drop(columns = [cliente])
    for otro_cliente, peso in distancias_cliente.items():
        df_resto[otro_cliente] = df_resto[otro_cliente] * peso

    return df_resto.sum(axis=1)

In [80]:
def recomendaciones_cliente(cliente):
    distancias_cliente = distancias_mes_19_21_22[cliente].drop(index = [cliente])
    df_resto = df_fecha_articulo_tabla_escalado.T.drop(columns = [cliente])
    for otro_cliente, peso in distancias_cliente.items():
        df_resto[otro_cliente] = df_resto[otro_cliente] * peso

    return df_resto.sum(axis=1)

In [86]:
recomendaciones_cliente('diciembre').sort_values(ascending=False).head(20)

chamarra         0.100486
bolsa            0.097020
pluma            0.088612
identificador    0.084452
cubrebocas       0.084102
libreta          0.083987
porta            0.077029
cosmetiquera     0.074004
soporte          0.072727
sombrilla        0.069669
encendedor       0.068066
termo            0.067361
reloj            0.063768
destapadores     0.058754
espejo           0.054607
vino             0.052393
pastillero       0.052289
banderines       0.050985
tarjeta          0.050619
mochila          0.048001
dtype: float64

In [84]:
x=0
for cliente in lista_mes:
    data_articulo = recomendaciones_cliente(cliente).sort_values(ascending=False)
    data_articulo = data_articulo.to_frame().reset_index()
    
    if x>0:
        data_articulo_total = data_articulo_total.merge(data_articulo, on= 'index', how= 'inner')
        
    if x==0:
        data_articulo_total = data_articulo.copy()
        x=x+1

C:\Users\sistemas\AppData\Local\Temp\ipykernel_12264\1598087027.py:7: FutureWarning: Passing 'suffixes' which cause duplicate columns {'0_x'} in the result is deprecated and will raise a MergeError in a future version.
  data_articulo_total = data_articulo_total.merge(data_articulo, on= 'index', how= 'inner')
C:\Users\sistemas\AppData\Local\Temp\ipykernel_12264\1598087027.py:7: FutureWarning: Passing 'suffixes' which cause duplicate columns {'0_x'} in the result is deprecated and will raise a MergeError in a future version.
  data_articulo_total = data_articulo_total.merge(data_articulo, on= 'index', how= 'inner')
C:\Users\sistemas\AppData\Local\Temp\ipykernel_12264\1598087027.py:7: FutureWarning: Passing 'suffixes' which cause duplicate columns {'0_x'} in the result is deprecated and will raise a MergeError in a future version.
  data_articulo_total = data_articulo_total.merge(data_articulo, on= 'index', how= 'inner')
C:\Users\sistemas\AppData\Local\Temp\ipykernel_12264\1598087027.py:7: FutureWarning: Passing 'suffixes' which cause duplicate columns {'0_x'} in the result is deprecated and will raise a MergeError in a future version.
  data_articulo_total = data_articulo_total.merge(data_articulo, on= 'index', how= 'inner')
C:\Users\sistemas\AppData\Local\Temp\ipykernel_12264\1598087027.py:7: FutureWarning: Passing 'suffixes' which cause duplicate columns {'0_x'} in the result is deprecated and will raise a MergeError in a future version.
  data_articulo_total = data_articulo_total.merge(data_articulo, on= 'index', how= 'inner')

In [85]:
data_articulo_total

,index,0_x,0_y,0_x,0_y,0_x,0_y,0_x,0_y,0_x,0_y,0_x,0_y
0,cilindro,0.117466,0.017668,-0.044679,0.022586,-0.068148,-0.025950,-0.090143,-0.019446,-0.030222,-0.027442,-0.028591,0.016727
1,cuchara,0.082173,0.034975,0.033485,0.014949,0.010309,0.012482,0.003682,0.033537,0.019689,-0.003108,0.003146,-0.224792
2,porta,0.082029,-0.042483,-0.093969,-0.109621,-0.020063,0.063805,-0.049174,-0.024825,-0.068008,-0.038906,0.015232,0.077029
3,encendedor,0.080535,-0.084136,-0.119312,0.055781,0.052465,-0.099149,0.064846,-0.020599,0.052851,0.070880,-0.026966,0.068066
4,banderines,0.077556,0.055599,-0.242292,0.041513,0.040836,0.039654,0.035285,0.036594,0.031888,0.043015,0.019898,0.050985
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,chaleco,-0.115988,0.064181,0.076293,0.035510,0.049100,0.050182,-0.112329,-0.081949,-0.029243,0.056504,0.024604,0.008628
99,parasol,-0.123378,0.063514,0.078522,0.027946,0.034720,0.030520,0.027718,0.052526,-0.040877,0.023679,0.016108,-0.091494
100,soporte,-0.126560,0.060452,0.090125,0.062426,-0.000537,0.088209,-0.069446,0.062052,0.060097,-0.078518,0.006723,0.072727
101,sombrilla,-0.143083,0.042795,0.074964,0.035935,0.052389,0.070833,-0.011487,0.046814,-0.082500,-0.108236,0.059922,0.069669
102,chamarra,-0.149927,-0.121977,0.086400,0.038159,0.035799,0.039907,0.038354,0.050060,0.023863,0.026586,0.026015,0.100486

In [88]:
data_articulo_total.columns = ['articulo', 'enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']

In [89]:
data_articulo_total

,articulo,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,cilindro,0.117466,0.017668,-0.044679,0.022586,-0.068148,-0.025950,-0.090143,-0.019446,-0.030222,-0.027442,-0.028591,0.016727
1,cuchara,0.082173,0.034975,0.033485,0.014949,0.010309,0.012482,0.003682,0.033537,0.019689,-0.003108,0.003146,-0.224792
2,porta,0.082029,-0.042483,-0.093969,-0.109621,-0.020063,0.063805,-0.049174,-0.024825,-0.068008,-0.038906,0.015232,0.077029
3,encendedor,0.080535,-0.084136,-0.119312,0.055781,0.052465,-0.099149,0.064846,-0.020599,0.052851,0.070880,-0.026966,0.068066
4,banderines,0.077556,0.055599,-0.242292,0.041513,0.040836,0.039654,0.035285,0.036594,0.031888,0.043015,0.019898,0.050985
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,chaleco,-0.115988,0.064181,0.076293,0.035510,0.049100,0.050182,-0.112329,-0.081949,-0.029243,0.056504,0.024604,0.008628
99,parasol,-0.123378,0.063514,0.078522,0.027946,0.034720,0.030520,0.027718,0.052526,-0.040877,0.023679,0.016108,-0.091494
100,soporte,-0.126560,0.060452,0.090125,0.062426,-0.000537,0.088209,-0.069446,0.062052,0.060097,-0.078518,0.006723,0.072727
101,sombrilla,-0.143083,0.042795,0.074964,0.035935,0.052389,0.070833,-0.011487,0.046814,-0.082500,-0.108236,0.059922,0.069669
102,chamarra,-0.149927,-0.121977,0.086400,0.038159,0.035799,0.039907,0.038354,0.050060,0.023863,0.026586,0.026015,0.100486

In [90]:
data_articulo_total.to_csv('lista_articulos_recomendacion_por_mes.csv', index=False, encoding='utf-8')